In [3]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

X,y = make_moons(n_samples = 1000, noise= 0.05)
dbscan = DBSCAN(eps = 0.05, min_samples = 5)
dbscan.fit(X)


DBSCAN(eps=0.05)

In [4]:
dbscan.labels_

array([ 0,  3,  1,  0,  0,  2,  3,  3, -1,  0,  3,  4,  4,  4,  0,  1,  0,
        3, -1,  5,  4,  4,  3,  1,  2,  3, -1, -1,  4,  0,  1,  4,  6, -1,
        4,  4,  7,  2,  2,  4,  4,  5,  8, -1,  0,  7,  4,  2,  8,  4, -1,
        7,  0,  4,  4,  3,  4,  4,  4, -1,  2,  6,  7,  4, -1,  3,  4,  4,
        7,  4,  6,  5,  6,  4,  3,  1,  4,  3,  4,  4,  4,  3,  3,  0,  2,
        4,  4,  1,  0,  2,  2,  5, -1,  4,  7,  2,  1, -1,  6,  3,  0,  0,
        4,  9,  3,  0,  2,  3,  4,  3,  4,  4,  4,  3,  4,  7,  0,  1,  1,
        3,  0,  4,  4,  4,  6,  1, -1,  3,  2,  4,  3,  4,  4,  1,  1,  0,
        3,  0, -1, -1,  3,  4,  7,  6,  4,  1,  2, -1,  4,  1,  3,  4,  3,
        0,  4,  2,  0,  4,  4,  2,  6,  3,  4, -1, -1,  0,  2,  0,  1,  7,
        4,  2,  4,  6,  0,  4, -1,  2,  3,  4,  4,  4,  4,  7, -1,  2,  6,
        4, -1,  4,  3,  1,  6,  4,  7,  4,  4,  6,  1,  3,  0,  9,  4,  0,
        4,  3,  4,  4,  1,  7, -1,  4,  9, -1,  6,  4,  2,  5, -1,  2,  3,
        4,  1,  2,  3,  2

In [5]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_,dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

In [6]:
import numpy as np
X_new = np.array([[-0.5,0],[0,0.5],[1,-0.1],[2,1]])
knn.predict(X_new)

array([1, 7, 4, 3])

In [7]:
knn.predict_proba(X_new)

array([[0.  , 0.8 , 0.  , 0.  , 0.  , 0.06, 0.  , 0.14, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.94, 0.06, 0.  , 0.  ],
       [0.  , 0.  , 0.46, 0.  , 0.54, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.76, 0.  , 0.  , 0.  , 0.  , 0.  , 0.24, 0.  ]])

In [8]:
y_dist,y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)
y_pred = dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]
y_pred[y_dist>0.2] = -1
y_pred.ravel()

array([-1,  8,  4, -1])

In [9]:
from sklearn.mixture import GaussianMixture

In [10]:
gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [12]:
gm.weights_
gm.means_

array([[ 0.50822383,  0.23655417],
       [-0.74245924,  0.56057928],
       [ 1.77441801, -0.03866345]])

In [15]:
gm.weights_

array([0.60414864, 0.20425686, 0.19159449])

In [16]:
gm.covariances_

array([[[ 0.17885401, -0.11189908],
        [-0.11189908,  0.29351605]],

       [[ 0.05446071,  0.06248783],
        [ 0.06248783,  0.08656954]],

       [[ 0.04145778,  0.05360998],
        [ 0.05360998,  0.08534678]]])

In [17]:
gm.converged_


True

In [19]:
gm.n_iter_

17

In [20]:
gm.predict_proba(X)

array([[1.00000000e+000, 1.53545542e-056, 4.62056673e-056],
       [8.60000589e-004, 1.32786039e-192, 9.99139999e-001],
       [1.66662941e-003, 9.98333371e-001, 1.34928637e-247],
       ...,
       [9.99968427e-001, 3.15734870e-005, 1.30304467e-162],
       [2.85504569e-004, 2.36401364e-218, 9.99714495e-001],
       [9.52892960e-002, 3.14797619e-202, 9.04710704e-001]],
      shape=(1000, 3))

In [22]:
X_new, y_new = gm.sample(6)
X_new

array([[-0.05517186, -0.3395047 ],
       [ 0.81800905,  0.28102592],
       [ 0.37522639,  0.95886984],
       [-0.91508445,  0.23472545],
       [ 1.54843271, -0.35075399],
       [ 1.82752394,  0.03775499]])

In [23]:
y_new

array([0, 0, 0, 1, 2, 2])

In [24]:
gm.score_samples(X)

array([-1.48444470e+00, -3.39489470e-01, -1.64478158e-01, -1.64244021e+00,
       -1.81476927e+00, -2.34131130e+00, -1.97322827e+00, -2.30342784e-01,
       -1.88273170e+00, -1.92121904e+00, -3.57458175e-01, -1.94201904e+00,
       -1.56138924e+00, -1.54150874e+00, -1.64749428e+00, -7.73166817e-01,
       -1.79374039e+00, -6.86013088e-01, -1.78008764e+00, -1.91312363e+00,
       -1.80480092e+00, -1.64978527e+00, -9.34296737e-01, -1.59155822e-01,
       -1.46407021e+00, -6.77439990e-01, -1.09489196e+00, -3.76495852e+00,
       -1.94268711e+00, -1.38283255e+00, -1.70524440e+00, -1.68147467e+00,
       -7.01171354e-01, -1.56623863e-01, -2.13664464e+00, -1.62171901e+00,
       -1.60160269e+00, -1.72187688e+00, -1.55817743e+00, -1.89301200e+00,
       -1.66214473e+00, -1.47853708e+00, -1.75544254e+00, -1.20740228e+00,
       -1.76285838e+00, -1.49412420e+00, -1.68589447e+00, -2.29697428e+00,
       -1.54357514e+00, -1.62684534e+00, -2.04565566e+00, -1.79343601e+00,
       -1.53531997e+00, -