In [1]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

X,y = make_moons(n_samples = 1000, noise= 0.05)
dbscan = DBSCAN(eps = 0.05, min_samples = 5)
dbscan.fit(X)


DBSCAN(eps=0.05)

In [2]:
dbscan.labels_

array([ 6,  0,  0,  0,  0,  1,  7,  0,  2,  4,  3,  4,  4,  5,  6,  4, -1,
        6,  4,  6,  0,  4,  0,  2,  2,  0,  1,  1,  4, -1,  1,  6,  0,  1,
        8,  8,  2,  4,  7,  6,  0,  0,  2,  2,  6, 12,  8,  4,  4,  6,  0,
        4,  4,  0,  1,  8,  4,  3,  6,  1,  3,  8,  3,  9,  0,  4,  0,  4,
        6,  0, -1,  4,  9,  6,  1,  1,  4,  8,  8, -1,  1,  6,  2,  8,  5,
        7,  3,  8,  4,  0,  6,  3,  8,  2,  6,  4,  1,  8,  0,  6,  0,  4,
        1,  7,  0,  1,  4,  4,  0,  0, -1,  5,  6,  4,  6,  9,  0,  4,  8,
        4,  5,  6,  8,  1,  0,  0,  6,  0,  2,  1,  4, 10,  2,  6,  4,  4,
        1,  4,  3,  1,  7,  0,  3, -1, -1,  1,  0,  0,  7,  8, -1,  1,  8,
        6,  6, 11,  0,  9,  3,  6,  4, 10, 10,  1,  6,  1,  3,  4,  1,  1,
        5, -1,  8, -1,  0,  4,  2,  3,  6,  0,  9,  6,  0,  4,  1,  6,  4,
        8,  6,  9,  3,  1,  4,  0,  2,  4,  5,  8,  4,  3,  2,  4,  1,  2,
        1,  6, -1,  4,  1,  3,  1,  0,  6,  0,  1,  1,  1,  6, 10,  6,  8,
       -1,  8,  0,  8,  0

In [3]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_,dbscan.labels_[dbscan.core_sample_indices_])

KNeighborsClassifier(n_neighbors=50)

In [4]:
import numpy as np
X_new = np.array([[-0.5,0],[0,0.5],[1,-0.1],[2,1]])
knn.predict(X_new)

array([4, 3, 2, 6])

In [5]:
knn.predict_proba(X_new)

array([[0.  , 0.  , 0.  , 0.1 , 0.54, 0.  , 0.  , 0.  , 0.  , 0.36, 0.  ,
        0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  ],
       [0.3 , 0.  , 0.66, 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.  , 0.  ,
        0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  ]])

In [6]:
y_dist,y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)
y_pred = dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]
y_pred[y_dist>0.2] = -1
y_pred.ravel()

array([-1,  3,  2, -1])

In [7]:
from sklearn.mixture import GaussianMixture

In [8]:
gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [9]:
gm.weights_
gm.means_

array([[ 1.72987356, -0.07293724],
       [-0.74677293,  0.56008823],
       [ 0.49102242,  0.26047962]])

In [10]:
gm.weights_

array([0.21290459, 0.20436225, 0.58273316])

In [11]:
gm.covariances_

array([[[ 0.05943761,  0.06677182],
        [ 0.06677182,  0.09224006]],

       [[ 0.05264907,  0.06077002],
        [ 0.06077002,  0.08525303]],

       [[ 0.1618108 , -0.09584093],
        [-0.09584093,  0.28132708]]])

In [12]:
gm.converged_


True

In [13]:
gm.n_iter_

15

In [14]:
gm.predict_proba(X)

array([[9.99782511e-001, 3.58136396e-194, 2.17489122e-004],
       [6.03815041e-008, 5.48266801e-126, 9.99999940e-001],
       [4.58764152e-031, 2.29377930e-066, 1.00000000e+000],
       ...,
       [8.85414941e-002, 6.13573564e-165, 9.11458506e-001],
       [7.91364191e-001, 4.31655325e-193, 2.08635809e-001],
       [9.99781846e-001, 5.58074387e-208, 2.18154060e-004]],
      shape=(1000, 3))

In [15]:
X_new, y_new = gm.sample(6)
X_new

array([[ 1.49949605, -0.3463652 ],
       [ 1.44323212, -0.27454921],
       [-0.68636153,  0.43897272],
       [ 0.17310931,  0.15473379],
       [ 0.50075716,  0.39100387],
       [ 0.35948829,  1.45678177]])

In [16]:
y_new

array([0, 0, 1, 2, 2, 2])

In [17]:
gm.score_samples(X)

array([-8.35886553e-01, -1.76983005e+00, -1.44191761e+00, -1.67640308e+00,
       -1.72567951e+00, -1.50065240e+00, -1.84921071e+00, -2.09052063e+00,
       -1.56423180e+00, -7.82472775e-01, -1.34471324e+00, -1.32720204e+00,
       -7.81023294e-02, -1.80078339e+00, -9.08213672e-01, -7.71696282e-01,
       -2.13312040e-01, -6.14025511e-01, -7.00764763e-01, -3.35420813e-01,
       -1.79608323e+00, -5.20208686e-01, -1.57155976e+00, -1.83046781e+00,
       -1.44768176e+00, -1.66389470e+00, -1.68322902e+00, -1.65260004e+00,
       -4.31402903e-01, -2.24662827e+00, -1.81185116e+00, -3.15802135e-02,
       -1.79592480e+00, -1.41276812e+00, -2.24460184e+00, -1.47643332e+00,
       -1.80158503e+00, -1.29300247e-01, -1.66951189e+00, -4.57060443e-01,
       -1.67253282e+00, -1.74423859e+00, -1.61389013e+00, -1.33476308e+00,
       -2.96113383e-01, -1.33143198e+00, -8.35886156e-01, -6.54783953e-01,
       -1.70848314e-01, -8.80089298e-01, -1.79857846e+00, -8.80874148e-01,
       -5.87010717e-01, -

In [18]:
densities = gm.score_samples(X)
density_threshold = np.percentile(densities,4)
anomalies = X[densities<density_threshold]

In [19]:
gm.bic(X)


2744.215527464004

In [20]:
gm.aic(X)
    

2660.7836877213076

In [21]:
from sklearn.mixture import BayesianGaussianMixture
bgm = BayesianGaussianMixture(n_init = 10, n_components=10)
bgm.fit(X)
np.round(bgm.weights_,2)

array([0.13, 0.11, 0.15, 0.17, 0.11, 0.11, 0.1 , 0.11, 0.  , 0.  ])